### ISSUE TITLE
The new defined cyclic colorscheme has a  highly oscillating lightness

### ISSUE THREAD

**Issue by empet** [eprovst/DomainColoring.jl#11]
Unfortunately your cyclic colorscheme, to represent complex functions through domain coloring
has the same drawbacks like HSV colormap, that has been used in most plots of complex functions across the web.
What makes HSV a bad colormap is not necessarily the fact that its lighting is not smooth, but because it is highly oscillating.
Perceptually uniform colormaps were defined for matplotlib, starting with 2015. The definition of  such a colormap/colorscheme  is summarized in a julia discourse thread, where there was presented another attempt to define a better cyclic colormap for complex functions [https://discourse.julialang.org/t/complex-colormap-in-julia-plots/84212/8](https://discourse.julialang.org/t/complex-colormap-in-julia-plots/84212/8).
At the moment a good cyclic colorscheme cannot be defined in pure Julia,
because  there is no package that   implements 
the color representation in the CAM02-UCS space or the most recent, CAM16-UCS space.
There is only a Python library, `colorspacious`, [https://github.com/njsmith/colorspacious](https://github.com/njsmith/colorspacious)
that can perform conversion from RGB to CAM02-UCS color appearance space, and conversely. 
The module  ehtplot [https://github.com/liamedeiros/ehtplot](https://github.com/liamedeiros/ehtplot), developed by scientists involved in the  Event Horizon Telescope project, before the first publication of 
a black hole image,   can assess the quality of a coloscheme, and moreover, provides functions to correct the non-linear lightness, i.e. to transform a bad one into a perceptually uniform colormap.

To compare the lightness of  your coloschemes, used in DomainColoring.jl, with pre-existent cyclic 
colorschmes defined  in different plotting libraries, I called the suitable functions from ehtplot to assess these colorschemes. For each one the lightness, chroma and hue  is represented in the CAM02-UCS space, versus the normalized angle values (i.e. the interval [-π, π], mapped to [0,1])
No one, excepting cmocean phase (see its representation in  the first link above) has a linear lightness, but all are  better than any colorscheme with a  highly oscillating  lightness.
![oscillating-lightness](https://github.com/eprovst/DomainColoring.jl/assets/3627253/26b5c87f-8c9b-4415-b9c6-831529c4faf2)
![cyclic-mpl-colorcet-fabio](https://github.com/eprovst/DomainColoring.jl/assets/3627253/843de1df-93cf-4245-a4e4-dc3910c273aa)

Finally a complex function is represented on the Riemann sphere, by domain coloring, using a few
cyclic colormaps, to compare how your colorscheme works in this context, too.
![Riemann-HSV eprovst](https://github.com/eprovst/DomainColoring.jl/assets/3627253/39dda710-b47b-4017-b8aa-469c48b9d1e2)
![Riemann-twilight colorcet](https://github.com/eprovst/DomainColoring.jl/assets/3627253/35c279f2-489a-4064-957e-99fd095de274)

**Comment by eprovst** [comment]
Hi, thank you for your thoughtful comments. Cyclic color maps nearly always inherently have some compromises, so let me explain the reasoning behind what we're doing here.

The main problem in the HSV map is the erraticness of everything, creating false detail, making certain parts of the phase look longer than others, etc. Unlike, HSV our peaks and troughs are at least equispaced, and smooth. Or, well, at least in as much as CIE L\*a\*b\* permits, once more recent models become available in the Julia world I'll be able to tweak the color map. The purples always felt a bit off, and here I see confirmation in your plots.

Highly oscillating feels somewhat exaggerated, lightnesswise the entire range is separated into six equal parts instead of two in the other examples. That is indeed three times as much, but I've generally felt like this places less emphasis on certain areas (brighter generally seems more important if you oscillate only once). The slope is similar to the other color maps, and some lightness variation is always needed, as our eyes mainly rely on lightness to discern higher frequency information [1]. 

The target color space is sRGB, so adding dips in lightness near its red, green, and blue primaries buys us more range in additional lightness variation to show magnitude in more complicated plots. Of course when only showing phase, this is not needed, but again, the color map is a compromise.

Finally, although this is not really an argument, expectations play a role, and at least in my experience, people are more willing to adopt something like my scheme (note that ColorCET's C6 is very similar) than something like romaO by Fabio Crameri [2] (which is the one I tend to use if only showing phase, to people I know have full color vision).

But, I agree that in a few ways my color scheme is not (or even far from) ideal, yet for the purposes in this package it was the best compromise I could come up with. I'm open to tweak it as I go though, and swapping out the color map is not too difficult if you only want a phase plot.

```julia
using DomainColoring

myshader(w) = colormap(mod(angle(w), 2π))
myplot(f, args...; kwargs...) = DomainColoring.shadedplot(f, myshader, args...; kwargs...)
```

Or analogously `DomainColoringToy.interactiveshadedplot` for `DomainColoringToy.jl`.

It might be helpful to document these compromises, and maybe provide alternatives which make other choices, so I'll keep this open for now.

Hope that addresses your concerns :slightly_smiling_face:

[1] Kovesi, Peter. (2015). “Good Colour Maps: How to Design Them.” arXiv:abs/1509.03700.
[2] Crameri, Fabio. (2023). Scientific colour maps (8.0.0). Zenodo. https://doi.org/10.5281/zenodo.8035877.

**Comment by empet** [comment]
I know both references, but nowadays someone creating new coloschemes should work in   newer color spaces. The coloschemes by Kovesi and Fabio Crameri are created in CIE L*a*b*, a +40 years old colorspace,  while the best coloschemes to date (viridis, plasma, magma, inferno, all cmocean  and cmasher coloschemes) are perceptually uniform in the space CAM02-UCS.
The coloscheme used by Ricky Reusser in domain coloring, [https://observablehq.com/@rreusser/domain-coloring-for-complex-functions](https://observablehq.com/@rreusser/domain-coloring-for-complex-functions), is generated in the newest color space, CAM16 [https://observablehq.com/@jrus/cam16](https://observablehq.com/@jrus/cam16)
The representation of  colorschemes by Kovesi and Crameri (implemented in Julia, too) in the space  CAM02-UCS are not perceptually uniform (their lightness is not linear).
![fabiocr-lightness](https://github.com/eprovst/DomainColoring.jl/assets/3627253/c135c40f-63e3-4b6a-a14e-e3aca6a08969)

CIECAM02 (CAM02) is a color appearence model designed by the International Commision on Illumination to accurately model human color perception, while CIECAM02-UCS is a transformation of CIECAM02 into a   perceptually uniform   space. Perceptual uniformity ensures  that Euclidean distance between colors, in the color space,  matches human color perception distance. 
![mpl-perc-unif-cmaps](https://github.com/eprovst/DomainColoring.jl/assets/3627253/cf19ff90-c526-488e-9f35-eccd29b1a4d2)
![cmocean-perc-unif-cmaps](https://github.com/eprovst/DomainColoring.jl/assets/3627253/d32269a5-65e3-40ef-9ca4-b222530f1ca9)

From this point of view should be obvious the    consequences of  lightness deviations from linearity, even uniform and symmetric  deviations.

**Comment by eprovst** [comment]
I agree that using newer color models would be preferable. The color map is not set in stone, so that's also possible, and the main issues I'm still facing with the current version are in the purple area which is highlighted by these newer models to be bad anyway. However, I'm still inclined to keep similar design decisions. It seems like Oklab is nearing inclusion into Colors.jl, which looks to work rather well for these purposes.

Also note that the color map used here is not meant to be used for highly detailed data analysis (not to say that we shouldn't strive to be as usable as possible), but more for easy visualisation of complex functions, so perceptual uniformity constraints are somewhat laxer. In a sense, the slight dead spots where the change in lightness flips sign, give some indication of where certain angles are. The point mainly being that these slight dead spots are in relevant places and smooth, rather than being all over the place and creating sharp ridges as in HSL.

Whilst indeed your first link uses the latest in color science, it seems to fail to stay within gamut and clips ever so slightly at pink and yellow, resulting in the appearance of ridges. This is exactly one of the reasons why we chose to have luminance dips at red, green and blue. Also, they seem to use an isoluminant map, which, to the best of my knowledge, are bad at displaying high frequency variations.

But indeed, CIE CAM02 predicts some issues which are not intentional, so in time I'd like to tweak the color map to have less of these.

**Comment by eprovst** [comment]
I documented the compromises and included a note on why it is less/not ideal for other uses than domain coloring. I also made pull requests into Colors.jl and ColorTypes.jl, adding support for Oklab (the latter of which has been merged), which in my internal testing gives somewhat better results.

Closing for now.
